version: '3.8'

services:
  final-go-kbtu:
    build: ./
    command: ./final-go-kbtu
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=poiu0987uiop

  db:
    restart: always
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=poiu0987uiop
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local